<?php
require_once("modals_examenes/general_orina.php");
require_once("modals_examenes/general_heces.php");
require_once("modals_examenes/trigliceridos.php");
require_once("modals_examenes/colesterol.php");
require_once("modals_examenes/glucosa.php");
require_once("modals_examenes/exofaringeo.php");
require_once("modals_examenes/hemograma.php");
require_once("modals_examenes/hemograma_edit.php");
require_once("modals_examenes/acido_urico.php");
require_once("modals_examenes/creatinina.php");
require_once("modals_examenes/sgot.php");
require_once("modals_examenes/sgpt.php");
?>